# https://github.com/QuantumObject/docker-zoneminder/issues/49#issuecomment-436931588
version: "3.7"
services:

  db:
    image: "mysql/mysql-server:5.7"
    environment:
      - TZ=America/Chicago
      - MYSQL_USER=zmuser
      - MYSQL_PASSWORD=zmpass
      - MYSQL_DATABASE=zm
      - MYSQL_ROOT_PASSWORD=testmysql
      - MYSQL_ROOT_HOST=
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/cache:/etc/mysql:ro"
    networks:
      - cctv

  zm:
    image: quantumobject/docker-zoneminder
    build:
      context: .
      shm_size: '2gb'
    environment:
      - TZ=America/Chicago
      - ZM_DB_HOST=testmysql.cpoalswsbhdf.us-east-1.rds.amazonaws.com
      - MYSQL_ROOT=testmysql
      - MYSQL_ROOT_PASSWORD=testmysql
      - SERVICE_PORTS="8081"
    volumes:
      - /var/empty
      - "./backups:/var/backups"
      - "./cache:/var/cache/zoneminder"
      - type: tmpfs
        target: /dev/shm
    networks:
      - cctv
    ports:
      - "8081:80"

networks:
  cctv:
    driver: bridge
